name: APIsec

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # Customize trigger events based on your DevSecOps processes.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '16 21 * * 2'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  Trigger APIsec scan:
    runs-on: ubuntu-latest

    steps:
       - name: APIsec scan
         uses: apisec-inc/apisec-run-scan@f62d0c6fae8a80f97b091a323befdb56e6ad9993
         with:
          # The APIsec username with which the scans will be executed
          apisec-username: ${{ secrets.apisec_username }}
          # The Password of the APIsec user with which the scans will be executed
          apisec-password: ${{ secrets.apisec_password}}
          # The name of the project for security scan
          apisec-project: "VAmPI"
          # The name of the sarif format result file The file is written only if this property is provided.
          sarif-result-file: "apisec-results.sarif"
       - name: Import results
         uses: github/codeql-action/upload-sarif@v1
         with:
          sarif_file: ./apisec-results.sarif
